# Generated by Django 2.1.5 on 2019-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=2)),
                ('sem', models.IntegerField()),
                ('sec', models.IntegerField()),
                ('usn', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
