# Generated by Django 2.1.5 on 2019-01-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0003_auto_20190121_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='attend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('p_b', models.NullBooleanField()),
                ('studentform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.studentform')),
            ],
        ),
    ]
