# Generated by Django 2.1.5 on 2019-01-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0005_attend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
