# Generated by Django 2.1.5 on 2019-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0006_auto_20190128_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='cources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cId', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('cfac', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=2)),
                ('sem', models.IntegerField()),
                ('sec', models.CharField(max_length=100)),
            ],
        ),
    ]
