# Generated by Django 2.1.5 on 2019-02-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0007_cources'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sample.cources'),
            preserve_default=False,
        ),
    ]
