# Generated by Django 2.1.5 on 2019-02-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0010_auto_20190204_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=100)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.cources')),
            ],
        ),
    ]
