# Generated by Django 2.1.5 on 2019-05-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0011_time_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cources',
            old_name='cId',
            new_name='LecID',
        ),
        migrations.RenameField(
            model_name='cources',
            old_name='cfac',
            new_name='Lec_name',
        ),
        migrations.RemoveField(
            model_name='cources',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='cources',
            name='faceimage',
        ),
        migrations.RemoveField(
            model_name='cources',
            name='sec',
        ),
    ]
