# Generated by Django 2.1.5 on 2019-05-05 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0012_auto_20190501_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='subject_id',
            new_name='lec_id',
        ),
        migrations.RenameField(
            model_name='time_table',
            old_name='timings',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='time_table',
            name='weekday',
        ),
        migrations.AddField(
            model_name='time_table',
            name='subject_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
