# Generated by Django 2.1.5 on 2019-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0013_auto_20190505_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
    ]
